CSWTest.App/Controllers/AuthorController.cs
using CSWTest.Storage;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CSWTest.App.Controllers
{
    public class AuthorController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult Get(int jtStartIndex = 0, int jtPageSize = 0)
        {
            try
            {
                var items = new AuthorService().Get(new Storage.SearchCriterias.AuthorSearchCriteria()
                {
                    Index = jtStartIndex,
                    PageSize = jtPageSize
                });
                return Json(new { Result = "OK", Records = items }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }


        public JsonResult GetOptions()
        {
            try
            {
                var items = new AuthorService().Get(new Storage.SearchCriterias.AuthorSearchCriteria()
                {
                    Index = 0,
                    PageSize = Int32.MaxValue
                })
                .Select(c => new { DisplayText = c.Name, Value = c.Id })
                .OrderBy(s => s.DisplayText);

                return Json(new { Result = "OK", Options = items }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }



        public JsonResult Post(Storage.Models.AuthorModel item)
        {
            try
            {
                item.Id = Guid.NewGuid();
                new AuthorService().Upsert(item);
                return Json(new { Result = "OK", Record = item });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        public JsonResult Put(Storage.Models.AuthorModel item)
        {
            try
            {
                new AuthorService().Upsert(item);
                return Json(new { Result = "OK", Record = item });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        public JsonResult Delete(Guid Id)
        {
            try
            {
                new AuthorService().Delete(Id); ;
                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }

        }
    }
}

CSWTest.App/Controllers/BookController.cs
using CSWTest.Storage;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CSWTest.App.Controllers
{
    public class BookController : Controller
    {
     //
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult Get(int jtStartIndex = 0, int jtPageSize = 0)
        {
            try
            {
                var items = new BookService().Get(new Storage.SearchCriterias.BookSearchCriteria()
                {
                    Index = jtStartIndex,
                    PageSize = jtPageSize
                });
                return Json(new { Result = "OK", Records = items }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult Post(Storage.Models.BookModel item, HttpPostedFileBase DocBytes)
        {
            try
            {
                if (item.IdAuthor == null)
                    throw new Exception("Author is expected.");
                if (item.IdCategory == null)
                    throw new Exception("Category is expected.");
                item.Id = Guid.NewGuid();
                item.Picture = Utils.WebUtils.GetB64File(DocBytes);
                new BookService().Upsert(item);
                return Json(new { Result = "OK", Record = item });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        public JsonResult Put(Storage.Models.BookModel item, HttpPostedFileBase DocBytes)
        {
            try
            {
                if (item.IdAuthor == null)
                    throw new Exception("Author is expected.");
                if (item.IdCategory == null)
                    throw new Exception("Category is expected.");

                var picture = Utils.WebUtils.GetB64File(DocBytes);
                if (!string.IsNullOrEmpty(picture))
                    item.Picture = picture;
                new BookService().Upsert(item);
                return Json(new { Result = "OK", Record = item });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        public JsonResult Delete(Guid Id)
        {
            try
            {
                new BookService().Delete(Id); ;
                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }

        }

    }
}

CSWTest.App/Controllers/CategoryController.cs
using CSWTest.Storage;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CSWTest.App.Controllers
{
    public class CategoryController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult Get(int jtStartIndex = 0, int jtPageSize = 0)
        {
            try
            {
                var items = new CategoryService().Get(new Storage.SearchCriterias.CategorySearchCriteria()
                {
                    Index = jtStartIndex,
                    PageSize = jtPageSize
                });
                return Json(new { Result = "OK", Records = items }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult GetOptions()
        {
            try
            {
                var items = new CategoryService().Get(new Storage.SearchCriterias.CategorySearchCriteria()
                {
                    Index = 0,
                    PageSize = Int32.MaxValue
                })
                .Select(c => new { DisplayText = c.Name, Value = c.Id })
                .OrderBy(s => s.DisplayText);

                return Json(new { Result = "OK", Options = items }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult Post(Storage.Models.CategoryModel item)
        {
            try
            {
                item.Id = Guid.NewGuid();
                new CategoryService().Upsert(item);
                return Json(new { Result = "OK", Record = item });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }



        public JsonResult Put(Storage.Models.CategoryModel item)
        {
            try
            {
                new CategoryService().Upsert(item);
                return Json(new { Result = "OK", Record = item });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        public JsonResult Delete(Guid Id)
        {
            try
            {
                new CategoryService().Delete(Id); ;
                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }

        }
    }
}

CSWTest.App/Views/Book/Index.cshtml
@{
    ViewBag.Title = "Books";
}

<div class="filter-bar">
    <div></div>
</div>
<div id="BookTableContainer"></div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#BookTableContainer').jtable({
            title: 'Books',
            columnResizable: false,
            paging: true,
            sorting: false,
            pageList: 'minimal',
            actions: {
                listAction: '@Url.Action("Get", "Book")',
                createAction: function (data) {
                    var deferred = $.Deferred();

                    // Capture form submit result from the hidden iframe
                    $("#postiframe").load(function () {
                        iframeContents = $("#postiframe").contents().find("body").text();
                        var result = $.parseJSON(iframeContents);
                        deferred.resolve(result);
                    });

                    // Submit form with file upload settings
                    var form = $('#jtable-create-form');
                    form.unbind("submit");
                    form.attr("action", "@Url.Action("Post", "Book")");
                    form.attr("method", "post");
                    form.attr("enctype", "multipart/form-data");
                    form.attr("encoding", "multipart/form-data");
                    form.attr("target", "postiframe");
                    form.submit();

                    return deferred;
                },
                updateAction: function (data) {
                    var deferred = $.Deferred();
                    var obj = JSON.parse('{"' + decodeURI(data).replace(/"/g, '\\"').replace(/&/g, '","').replace(/=/g, '":"') + '"}')
                    // Capture form submit result from the hidden iframe
                    $("#postiframe").load(function () {
                        iframeContents = $("#postiframe").contents().find("body").text();
                        var result = $.parseJSON(iframeContents);
                        deferred.resolve(result);
                    });

                    // Submit form with file upload settings
                    var form = $('#jtable-edit-form');
                    form.unbind("submit");
                    form.attr("action", "@Url.Action("Put", "Book")");
                    form.attr("method", "post");
                    form.attr("enctype", "multipart/form-data");
                    form.attr("encoding", "multipart/form-data");
                    form.attr("target", "postiframe");
                    form.submit();

                    return deferred;
                },
                deleteAction: '@Url.Action("Delete", "Book")'
            },
            fields: {
                Id: {
                    key: true,
                    list: false
                },
                Name: {
                    title: 'Book Name'
                },
                Summary: {
                    title: 'Summary'
                },
                IdAuthor: {
                    title: 'Author',
                    options: '@Url.Action("GetOptions", "Author")',
                    list: true
                },
                IdCategory: {
                    title: 'Category',
                    options: '@Url.Action("GetOptions", "Category")',
                    list: true
                },
                Price: {
                    title: 'Price'
                },
                DocBytes: {
                    title: "Picture",
                    list: false,
                    create: true,
                    input: function (data) {
                        return '<input id="DocBytes" type="file" name="DocBytes" /><iframe name="postiframe" id="postiframe" style="display: none" />';
                    }
                },
                Image: {
                    title: "Image",
                    list: true,
                    create: false,
                    edit: false,
                    display: function (data) {
                        if (data.record.Picture != null) {
                            return '<img class="preview-img" src="data:image/jpeg;base64,' + data.record.Picture + '" />';
                        }
                        else {
                            return '<div class="no-image"></div> ';
                        }
                    }
                }
            }
        });

        $('#BookTableContainer').jtable('load');
    });


</script>